workflows:
  ios-testflight:
    name: Varda Dienas iOS TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Varda
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nialldbarber.vardadienas
      vars:
        XCODE_WORKSPACE: "VardaDienas.xcworkspace"
        XCODE_SCHEME: "VardaDienas"
        APP_ID: 6747011314
      node: v19.7.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios
          if [ ! -f *.xcodeproj/project.pbxproj ] && [ ! -f *.xcworkspace ]; then
            echo "Error: No Xcode project found in $(pwd)"
            ls -la
            exit 1
          fi
          echo "Fetching latest build number from TestFlight..."
          if LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID" 2>/dev/null); then
            echo "Latest TestFlight build number: $LATEST_BUILD_NUMBER"
            if ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
              echo "Warning: Invalid build number format received: $LATEST_BUILD_NUMBER"
              echo "Falling back to current project build number"
              LATEST_BUILD_NUMBER=$(agvtool what-version -terse 2>/dev/null || echo "0")
            fi
          else
            echo "Warning: Failed to fetch TestFlight build number"
            echo "Falling back to current project build number"
            LATEST_BUILD_NUMBER=$(agvtool what-version -terse 2>/dev/null || echo "0")
          fi
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "Setting new build number to: $NEW_BUILD_NUMBER"
          if agvtool new-version -all $NEW_BUILD_NUMBER; then
            echo "✅ Build number successfully updated"
          else
            echo "❌ Failed to set build number"
            exit 1
          fi
          CURRENT_BUILD_NUMBER=$(agvtool what-version -terse)
          echo "Verification - Current build number: $CURRENT_BUILD_NUMBER"
          if [ "$CURRENT_BUILD_NUMBER" != "$NEW_BUILD_NUMBER" ]; then
            echo "❌ Build number verification failed"
            echo "Expected: $NEW_BUILD_NUMBER, Got: $CURRENT_BUILD_NUMBER"
            exit 1
          fi
          echo "✅ Build number successfully set and verified"
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - nialldbarber@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Vardu Kalendārs Test Group

    ios-production:
        name: Varda Dienas iOS App Store
        max_build_duration: 120
        instance_type: mac_mini_m2
        integrations:
            app_store_connect: Varda
        environment:
            ios_signing:
                distribution_type: app_store
                bundle_identifier: com.nialldbarber.vardadienas
            vars:
                XCODE_WORKSPACE: "VardaDienas.xcworkspace"
                XCODE_SCHEME: "VardaDienas"
                APP_ID: 6747011314
            node: v19.7.0
            xcode: latest
            cocoapods: default
        scripts:
            - name: Install npm dependencies
              script: |
                npm install
            - name: Install CocoaPods dependencies
              script: |
                cd ios && pod install
            - name: Set up code signing settings on Xcode project
              script: |
                xcode-project use-profiles --warn-only
            - name: Increment build number
              script: |
                cd $CM_BUILD_DIR/ios
                
                # Verify we're in the right directory
                if [ ! -f *.xcodeproj/project.pbxproj ] && [ ! -f *.xcworkspace ]; then
                  echo "Error: No Xcode project found in $(pwd)"
                  ls -la
                  exit 1
                fi
                
                # Get the latest build number from TestFlight with error handling
                echo "Fetching latest build number from TestFlight..."
                if LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID" 2>/dev/null); then
                  echo "Latest TestFlight build number: $LATEST_BUILD_NUMBER"
                  
                  # Validate that we got a numeric value
                  if ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
                    echo "Warning: Invalid build number format received: $LATEST_BUILD_NUMBER"
                    echo "Falling back to current project build number"
                    LATEST_BUILD_NUMBER=$(agvtool what-version -terse 2>/dev/null || echo "0")
                  fi
                else
                  echo "Warning: Failed to fetch TestFlight build number"
                  echo "Falling back to current project build number"
                  LATEST_BUILD_NUMBER=$(agvtool what-version -terse 2>/dev/null || echo "0")
                fi
                
                # Increment by 1
                NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
                echo "Setting new build number to: $NEW_BUILD_NUMBER"
                
                # Set the new build number with error handling
                if agvtool new-version -all $NEW_BUILD_NUMBER; then
                  echo "✅ Build number successfully updated"
                else
                  echo "❌ Failed to set build number"
                  exit 1
                fi
                
                # Verify the change
                CURRENT_BUILD_NUMBER=$(agvtool what-version -terse)
                echo "Verification - Current build number: $CURRENT_BUILD_NUMBER"
                
                # Double-check that the number was actually updated
                if [ "$CURRENT_BUILD_NUMBER" != "$NEW_BUILD_NUMBER" ]; then
                  echo "❌ Build number verification failed"
                  echo "Expected: $NEW_BUILD_NUMBER, Got: $CURRENT_BUILD_NUMBER"
                  exit 1
                fi
                
                echo "✅ Build number successfully set and verified"
            - name: Build ipa for distribution
              script: |
                xcode-project build-ipa \
                  --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                  --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
        publishing:
            email:
                recipients:
                    - nialldbarber@gmail.com
                notify:
                    success: true
                    failure: false
            app_store_connect:
                auth: integration
                submit_to_testflight: false
                submit_to_app_store: true
        triggering:
            events:
                - tag
            tag_patterns:
                - pattern: 'v*.*.*'
                  include: true